# Public: Defines a boolean attribute for the model.
#
# name - The Symbol name of the attribute.
# opts - The Hash options used to refine the attribute (default: {}):
#        :doc_values - The Boolean indicating if the field should be stored on disk in a column-stride fashion.
#                      This allows it to be used later for sorting, aggregations, or scripting. Defaults to true.
#        :index - The Boolean indicating if the field should be quickly searchable. Defaults to true.
#        :ignore_malformed - The Boolean indicating if exceptions thrown when trying to index the wrong data type into a field should be ignored. Defaults to false.
#        :null_value - The Boolean value to be substituted for any explicit null values. Defaults to null.
#        :on_script_error - The String defining what to do if the script defined by the :script parameter throws an error at indexing time. Can be 'fail' or 'continue'.
#        :script - The String script that will index values generated by this script, rather than reading the values directly from the source.
#        :store - The Boolean indicating if the field value should be stored and retrievable separately from the _source field. Defaults to false.
#        :meta - The Hash metadata about the field.
#
# Examples
#
#   class MyModel
#     include StretchyModel
#     attribute :name, :boolean, doc_values: true, store: true
#   end
#
# Returns nothing.
module Stretchy
  module Attributes
    module Type
      class Boolean < Stretchy::Attributes::Type::Base

        OPTIONS = [:doc_values, :index, :ignore_malformed, :null_value, :on_script_error, :script, :store, :meta]
        attr_reader *OPTIONS 

        def initialize(**args)  
          args.each do |k, v|
            instance_variable_set("@#{k}", v) if OPTIONS.include?(k)
            args.delete(k)
          end
          super
        end

        def type
          :boolean
        end



      end
    end
  end
end