module Stretchy::Attributes::Type
  # Public: Defines a datetime attribute for the model.
  #
  # opts - The Hash options used to refine the attribute (default: {}):
  #        :doc_values - The Boolean indicating if the field should be stored on disk in a column-stride fashion.
  #                      This allows it to be used later for sorting, aggregations, or scripting. Defaults to true.
  #        :format - The String date format(s) that can be parsed. Defaults to 'strict_date_optional_time||epoch_millis'.
  #        :locale - The String locale to use when parsing dates. Defaults to the ROOT locale.
  #        :ignore_malformed - The Boolean indicating if malformed numbers should be ignored. Defaults to false.
  #        :index - The Boolean indicating if the field should be quickly searchable. Defaults to true.
  #        :null_value - The Date value to be substituted for any explicit null values. Defaults to null.
  #        :on_script_error - The String defining what to do if the script defined by the :script parameter throws an error at indexing time. Can be 'fail' or 'continue'.
  #        :script - The String script that will index values generated by this script, rather than reading the values directly from the source.
  #        :store - The Boolean indicating if the field value should be stored and retrievable separately from the _source field. Defaults to false.
  #        :meta - The Hash metadata about the field.
  #
  # Examples
  #
  #   class MyModel < Stretchy::Record
  #     attribute :created_at, :datetime, format: 'strict_date_optional_time||epoch_millis', locale: 'en'
  #   end
  #
  # Returns nothing.
  class DateTime < Stretchy::Attributes::Type::Base
    OPTIONS = [:doc_values, :format, :locale, :ignore_malformed, :index, :null_value, :on_script_error, :script, :store, :meta]
    attr_reader *OPTIONS
    def type
      :datetime
    end
  end
end