module Stretchy::Attributes::Type
  # Public: Defines a geo_point attribute for the model.
  #
  # opts - The Hash options used to refine the attribute (default: {}):
  #        :ignore_malformed - The Boolean indicating if malformed geopoints should be ignored. Defaults to false.
  #        :ignore_z_value - The Boolean indicating if three dimension points should be accepted but only latitude and longitude values should be indexed. Defaults to true.
  #        :index - The Boolean indicating if the field should be quickly searchable. Defaults to true.
  #        :null_value - The GeoPoint value to be substituted for any explicit null values. Defaults to null.
  #        :on_script_error - The String defining what to do if the script defined by the :script parameter throws an error at indexing time. Can be 'fail' or 'continue'.
  #        :script - The String script that will index values generated by this script, rather than reading the values directly from the source.
  #
  # Examples
  #
  #   class MyModel
  #     include StretchyModel
  #     attribute :location, :geo_point, ignore_malformed: true
  #   end
  #
  # Returns nothing.
  class GeoPoint < Stretchy::Attributes::Type::Base
    OPTIONS = [:ignore_malformed, :ignore_z_value, :index, :null_value, :on_script_error, :script]

    def type
      :geo_point
    end
  end
end