module Stretchy::Attributes::Type
  # The IP attribute type
  #
  # This class is used to define an IP attribute for a model. It provides support for the Elasticsearch IP data type, which is a type of data type that can hold IPv4 and IPv6 addresses.
  #
  # ### Parameters
  #
  # - `type:` `:ip`.
  # - `options:` The Hash of options for the attribute.
  #    - `:doc_values:` The Boolean indicating if the field should be stored on disk in a column-stride fashion. Defaults to true.
  #    - `:ignore_malformed:` The Boolean indicating if malformed IP addresses should be ignored. Defaults to false.
  #    - `:index:` The Boolean indicating if the field should be quickly searchable. Defaults to true.
  #    - `:null_value:` The String IPv4 or IPv6 value to be substituted for any explicit null values. Defaults to null.
  #    - `:on_script_error:` The String defining what to do if the script defined by the :script parameter throws an error at indexing time. Can be 'reject' or 'ignore'.
  #    - `:script:` The String script that will index values generated by this script, rather than reading the values directly from the source.
  #    - `:store:` The Boolean indicating if the field value should be stored and retrievable separately from the _source field. Defaults to false.
  #    - `:time_series_dimension:` The Boolean indicating if the field is a time series dimension. Defaults to false.
  #
  # ---
  #
  # ### Examples
  #
  # #### Define an IP attribute
  #
  # ```ruby
  #   class MyModel < StretchyModel
  #     attribute :ip_address, :ip, ignore_malformed: true, time_series_dimension: true
  #   end
  # ```
  #
  class IP < Stretchy::Attributes::Type::Base
    OPTIONS = [:doc_values, :ignore_malformed, :index, :null_value, :on_script_error, :script, :store, :time_series_dimension]

    def type
      :ip
    end
  end
end