module Stretchy::Attributes::Type
  # The Wildcard attribute type
  #
  # This class is used to define a wildcard attribute for a model. This field type is a specialization of the keyword field, but it supports wildcard searches.
  #
  # ### Parameters
  #
  # - `type:` `:wildcard`.
  # - `options:` The Hash of options for the attribute.
  #    - `:doc_values:` The Boolean indicating if the field should be stored on disk in a column-stride fashion. Defaults to true.
  #    - `:eager_global_ordinals:` The Boolean indicating if global ordinals should be loaded eagerly on refresh. Defaults to false.
  #    - `:fields:` The Hash of multi-fields for the same string value to be indexed in multiple ways.
  #    - `:ignore_above:` The Integer limit for the length of the string. Strings longer than this limit will not be indexed. Defaults to 2147483647.
  #    - `:index:` The Boolean indicating if the field should be quickly searchable. Defaults to true.
  #    - `:index_options:` The String indicating what information should be stored in the index for scoring purposes. Defaults to 'docs'.
  #    - `:meta:` The Hash metadata about the field.
  #    - `:norms:` The Boolean indicating if field-length should be taken into account when scoring queries. Defaults to false.
  #    - `:null_value:` The String value to be substituted for any explicit null values. Defaults to null.
  #    - `:on_script_error:` The String defining what to do if the script defined by the :script parameter throws an error at indexing time. Can be 'fail' or 'continue'.
  #    - `:script:` The String script that will index values generated by this script, rather than reading the values directly from the source.
  #    - `:store:` The Boolean indicating if the field value should be stored and retrievable separately from the _source field. Defaults to false.
  #    - `:similarity:` The String scoring algorithm or similarity to be used. Defaults to 'BM25'.
  #    - `:normalizer:` The String pre-processor for the keyword prior to indexing. Defaults to null.
  #    - `:split_queries_on_whitespace:` The Boolean indicating if full text queries should split the input on whitespace. Defaults to false.
  #    - `:time_series_dimension:` The Boolean indicating if the field is a time series dimension. Defaults to false.
  #
  # ---
  #
  # ### Examples
  #
  # #### Define a wildcard attribute
  #
  # ```ruby
  #   class MyModel < StretchyModel
  #     attribute :description_wildcard, :wildcard
  #   end
  # ```
  #
  class Wildcard < Stretchy::Attributes::Type::Keyword
    OPTIONS = [:doc_values, :eager_global_ordinals, :fields, :ignore_above, :index, :index_options, :meta, :norms, :null_value, :on_script_error, :script, :store, :similarity, :normalizer, :split_queries_on_whitespace, :time_series_dimension]
    attr_reader *OPTIONS
    def type
      :wildcard
    end
  end
end