name: Release Gem

on:
  push:
    branches: 
      - main
    tags:
      - 'v*'
    paths: 
      - 'lib/stretchy/version.rb'


jobs:
  # spec:
    # uses: ./.github/workflows/spec.yml

  build:
    runs-on: ubuntu-latest
    # needs: spec

    steps:
      - uses: actions/checkout@v4

      - name: Publish gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
