name: Ruby CI

on: 
  pull_request:

jobs:
  elasticsearch:

    runs-on: ${{matrix.os}}-latest

    strategy:
      matrix:
        os: ['ubuntu']
        ruby: ['3.1', '2.7']
        elasticsearch: ['7.x-SNAPSHOT', '8.12.2']
        # opensearch: ['2.12.0']


    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Increase system limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Set up Elasticsearch ${{ matrix.elasticsearch }}
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: ${{matrix.elasticsearch}}
          security-enabled: false
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec

  opensearch:
  
      runs-on: ${{matrix.os}}-latest
      # services: 
      #   opensearch: 
      #     image: opensearchproject/opensearch:2
      #     ports: 
      #       - 9200:9200
      #     env:
      #       discovery.type: single-node
      #       OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      #       DISABLE_INSTALL_DEMO_CONFIG: true
      #       DISABLE_SECURITY_PLUGIN: true
      #       bootstrap.memory_lock: true

      strategy:
        matrix:
          os: ['ubuntu']
          ruby: ['3.1']
          opensearch: ['2.12.0']

      env:
        BACKEND: opensearch
        OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
        DISABLE_INSTALL_DEMO_CONFIG: true

      steps:
        - uses: actions/checkout@v4
        - name: Set up OpenSearch ${{ matrix.opensearch }}
          uses: theablefew/opensearch-github-actions/opensearch@main
          with:
            version: ${{ matrix.opensearch }}
            security-disabled: true

        - name: Set up Ruby ${{ matrix.ruby }}
          uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
          with:
            ruby-version: ${{ matrix.ruby }}

        - name: Install dependencies
          run: bundle install
        - name: Run tests
          run: bundle exec rspec