name: Ruby CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{matrix.os}}-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        env: 
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ports:  
        - 9200:9200

    strategy:
      matrix:
        os: ['ubuntu']
        ruby: ['3.1', '3.0', '2.7']
        elasticsearch: ['6.8.2', '7.10.1', '8.12.2']
        opensearch: ['2.12.0']


    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
